const mongoose = require('mongoose');
const fs = require('fs');

// 1. Import your existing Anime model
const Anime = require('./Model/AnimeModel');

// 2. Your MongoDB connection string (grabbed from your earlier terminal screenshot)
const MONGO_URI = 'mongodb://127.0.0.1:27017/okaturate';

async function seedDatabase() {
    try {
        console.log('⏳ Connecting to the database...');
        await mongoose.connect(MONGO_URI);
        console.log('✅ Connected to MongoDB!');

        console.log('⏳ Reading the newly fetched Jikan anime data...');
        // Read the JSON file generated by fetch_jikan.js
        const rawData = fs.readFileSync('./dataset/top_1000_anime.json', 'utf-8');
        const jikanData = JSON.parse(rawData);

        console.log(`🚀 Formatting ${jikanData.length} records to match your schema...`);

  const formattedData = jikanData.map(anime => ({
            kaggle_uid: anime.id,
            title: anime.title,
            genre: anime.genres,
            image: anime.image_url,
            rating: anime.rating,          
            episodes: anime.episodes,      
            studio: anime.studio,             // Now pulls the real studio
            status: anime.status,             // Now pulls the real status
            description: anime.description,   // Now pulls the real synopsis
            release_year: anime.release_year  // Now pulls the real year
        }));

// WIPE THE OLD DATA FIRST
        await Anime.deleteMany({});
        console.log('🧹 Cleared old anime data.');

        console.log('💾 Inserting data into MongoDB...');
        await Anime.insertMany(formattedData);
        console.log('🎉 Successfully seeded the database with top 1000 anime!');
    } catch (error) {
        console.error('❌ Error seeding database:', error);
    } finally {
        // 4. Always close the connection when done
        mongoose.connection.close();
        console.log('🔌 Database connection closed.');
    }
}

seedDatabase();